# Generated by Django 2.1.5 on 2019-02-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='provide a beer name', max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Beer',
                'verbose_name_plural': 'Beers',
            },
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='provide a beer type like lagger, pilsen, etc.', max_length=128, verbose_name='beer type')),
            ],
            options={
                'verbose_name': 'Beer Type',
                'verbose_name_plural': 'Beer Types',
            },
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='core.BeerType'),
        ),
    ]
